# generated by datamodel-codegen:
#   filename:  frame_analytics.schema.json
#   timestamp: 2026-03-17T17:01:31+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Point(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class Vector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float
    magnitude: float


class DoublePoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x1: float
    y1: float
    x2: float
    y2: float


class LineSegment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    coords: DoublePoint
    magnitude: float


class BodyLayoutType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    BodyBbox: List[Optional[DoublePoint]]
    BodyCenter: List[Optional[Point]]
    HorizontalBodyCenterline: List[Optional[DoublePoint]]
    VerticalBodyCenterline: List[Optional[DoublePoint]]
    UpperBodyBbox: List[Optional[DoublePoint]]
    UpperBodyCenter: List[Optional[Point]]
    UpperHorizontalBodyCenterline: List[Optional[DoublePoint]]
    UpperVerticalBodyCenterline: List[Optional[DoublePoint]]
    LowerBodyBbox: List[Optional[DoublePoint]]
    LowerBodyCenter: List[Optional[Point]]
    LowerHorizontalBodyCenterline: List[Optional[DoublePoint]]
    LowerVerticalBodyCenterline: List[Optional[DoublePoint]]


class BodyDistancesType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    LeftArmReach: List[Optional[Vector]]
    RightArmReach: List[Optional[Vector]]
    LeftLegReach: List[Optional[Vector]]
    RightLegReach: List[Optional[Vector]]
    HandsDistance: List[Optional[LineSegment]]
    FeetDistance: List[Optional[LineSegment]]
    LeftSideDistance: List[Optional[LineSegment]]
    RightSideDistance: List[Optional[LineSegment]]
    FallDiagonal: List[Optional[LineSegment]]
    RiseDiagonal: List[Optional[LineSegment]]


class CoMType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Position: List[Optional[Point]]
    Velocity: List[Optional[Vector]]
    Acceleration: List[Optional[Vector]]
    Jerk: List[Optional[Vector]]
    DistanceToBC: List[Optional[Vector]]


class JointAnglesType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    LeftArmpit: List[Optional[float]]
    RightArmpit: List[Optional[float]]
    LeftElbow: List[Optional[float]]
    RightElbow: List[Optional[float]]
    LeftHip: List[Optional[float]]
    RightHip: List[Optional[float]]
    LeftKnee: List[Optional[float]]
    RightKnee: List[Optional[float]]


class KeypointVelocitiesType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    LeftShoulder: List[Optional[Vector]]
    RightShoulder: List[Optional[Vector]]
    LeftElbow: List[Optional[Vector]]
    RightElbow: List[Optional[Vector]]
    LeftWrist: List[Optional[Vector]]
    RightWrist: List[Optional[Vector]]
    LeftHip: List[Optional[Vector]]
    RightHip: List[Optional[Vector]]
    LeftKnee: List[Optional[Vector]]
    RightKnee: List[Optional[Vector]]
    LeftAnkle: List[Optional[Vector]]
    RightAnkle: List[Optional[Vector]]


class WallContactsType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    LeftHand: List[int]
    RightHand: List[int]
    LeftFoot: List[int]
    RightFoot: List[int]


class FrameAnalyticsData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    BodyLayout: BodyLayoutType
    BodyDistances: BodyDistancesType
    CoM: CoMType
    JointAngles: JointAnglesType
    JointAngleVelocities: JointAnglesType
    KeypointVelocities: KeypointVelocitiesType
    WallContacts: WallContactsType
