# generated by datamodel-codegen:
#   filename:  summary.schema.json
#   timestamp: 2026-01-02T14:57:42+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class HoldUsageSummary(BaseModel):
    class Config:
        extra = Extra.forbid

    limb0: float
    limb1: float
    limb2: float
    limb3: float
    limb4: float


class HoldUsageMap(BaseModel):
    class Config:
        extra = Extra.forbid

    left_hand: List[int]
    right_hand: List[int]
    left_foot: List[int]
    right_foot: List[int]


class SummaryData(BaseModel):
    class Config:
        extra = Extra.forbid

    HoldUsageSummary: HoldUsageSummary
    HoldUsageMap: HoldUsageMap
