# generated by datamodel-codegen:
#   filename:  summary.schema.json
#   timestamp: 2026-01-28T15:22:03+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Extra


class HoldUsageSummary(BaseModel):
    class Config:
        extra = Extra.forbid

    limb0: float
    limb1: float
    limb2: float
    limb3: float
    limb4: float


class HoldUsageMap(BaseModel):
    class Config:
        extra = Extra.forbid

    left_hand: List[int]
    right_hand: List[int]
    left_foot: List[int]
    right_foot: List[int]


class RouteSegmentationItem(BaseModel):
    class Config:
        extra = Extra.forbid

    start_frame: int
    end_frame: int
    limb_index: int
    hold_from: int
    hold_to: int


class SummaryData(BaseModel):
    class Config:
        extra = Extra.forbid

    HoldUsageSummary: HoldUsageSummary
    HoldUsageMap: HoldUsageMap
    RouteSegmentation: List[RouteSegmentationItem]
    FrameMoveMap: List[int]
